### ISSUE TITLE
피그마 디자인 변경 바탕 레이아웃 수정

### ISSUE THREAD

**Issue by hookor** [FastCampus-Mini5/FE-temp#21]
## Todo
- [ ] 헤더 아래 border-bottom 구현
- [ ] 프로필 sectioning 세부정렬
- [ ] 헤더 여백 정렬?(차후)
- [ ] 연차/당직 신청 레이아웃
- [ ] 푸터 논의
- [ ] non-header 깨짐 수정
- [ ] 프로필 수정 세부 조율(본인 파트, 차후)
- [ ] 회원가입 페이지 입사날짜란 추가
