### ISSUE TITLE
Header 부분 스타일 및 기능 추가

### ISSUE THREAD

**Issue by hahahaday12** [FastCampus-Mini5/FE-temp#8]
## Todo
- [x] Header 카테고리 스타일 추가
- [x] Header 카테고리 라우터 기능 추가 
- [x] 라우터 추가 연결

**Comment by hahahaday12** [comment]
Merged 완료
